services:

  traccar:
    image: traccar/traccar:latest
    container_name: traccar
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    ports:
      - "8082:8082"
      - "5000-5500:5000-5500"
      - "5000-5150:5000-5150/udp"
    volumes:
      - /traccar/logs:/opt/traccar/logs:rw
      - /traccar/data:/opt/traccar/data:rw
